stages:
 - release

variables:
  MVN_RELEASE_TAG: "@(project.version)-*"

release:
  stage: release
  image: maven:3.6.3-jdk-11
  script:
    -  git clone https://root:glpat-FUxW549x1jebmawpsa9B@gitlab.com/yassermagdy430/java-maven-app.git
    -  cd ./$CI_PROJECT_NAME
    -  git config user.name root
    -  git config user.email yassermagdy430@gmail.com
    -  echo $CI_COMMIT_MESSAGE
    #- mvn release:prepare
    - |
      if   [[ $CI_COMMIT_MESSAGE == *"bugfix"* ]]
      then
        echo "bug"
        mvn versions:set  -DnewVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{OFS="."; $3=$3+1; print $0}')

      # then
      #   mvn versions:set -DnewVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. '{OFS="."; $2++; $3=0; print $0}')
      fi
    - mvn clean install
    - mvn release:prepare -B -DautoVersionSubmodules=true -DdevelopmentVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)-SNAPSHOT
    - mvn release:perform -B -DskipTests
  
   # - mvn release:perform
