stages:
 - release
 - build

release:
  stage: release
  image: maven:3.6.3-jdk-11
  script:
    -  git clone https://root:glpat-FUxW549x1jebmawpsa9B@gitlab.com/yassermagdy430/java-maven-app.git
    -  cd ./$CI_PROJECT_NAME
    -  git config user.name root
    -  git config user.email yassermagdy430@gmail.com
    -  echo $CI_COMMIT_MESSAGE
    #- mvn release:prepare
    - |
      if [ CI_COMMIT_MESSAGE == *"bugfix"* ]; then
        mvn release:prepare
      elif [ CI_COMMIT_MESSAGE == *"feature"* ];
        mvn release:prepare -DincrementMinorVersion=true
      fi

      # if [[ -n $RELEASE_TYPE ]]
      # then
      #   mvn  release:update-versions -DautoVersionSubmodules=true -DupdateMatchingVersions=true -DreleaseType=$RELEASE_TYPE release:prepare
      # fi
      # - find . -name "pom.xml" -exec sed -i "s/<version>.*<\/version>/<version>$new_version<\/version>/g" {} \;
      # - git add */pom.xml
      # - echo "New version: $new_version"
