name: my_first_java_app

services:
  java-maven-app:
    image: victornta32/my-repo:jma-2.0
    ports:
      - "8080:8080"
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb