version: '3.8'
services:
  jave-maven-app:
    image: ${image}
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Dot@2020
