
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ESXdOakEwTkRJeU1Wb1hEVE15TURJd05EQTBOREl5TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk8rCkJMVUh1bzVGUVlsSytJTkFKU3FUc0pLQVVrQ0JGU2c1c2Q5dXRDYld6TXE5QWphVW1WRDZ4Qzd2dzVpQmpaY00KQU1nczllb3MwSTd5WUlpZGxyTlZOZ3E5QjU2OWRJNmRWU1ZpL1VKc1JtTWhGVHkxanRzTGEzaXVjMHBkWHE1SgpndldhdHRjQnBZak1iYWl3TVhyZFYwWUp6d0JOMk5VbGhHV09NNXFGVWhEdkVlUkVNSVdoKzN2Y2Q0RDc1ZGcwCmM2dFhwRnBUd04vQVJOQTJrUXNYbkdnMUYwSDJDd1NrbXpWaVpGdHM2azhITlRUdFY5a3Rxa0JVd1hzMllkUTAKc29VRzVzYVJOT0N4U1BLSm8zZVhMeVczdVJRcDdtbjErZjU3RktRNXB4dlg4ekVheU0wTkRRc0tSVFB6b1R4aAp2RUwxcXFGbmhBQVVvSDJucmZVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBZzVHQlZ3NGhCd3MyQW5xVEMxRzBtaUxnWm1NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBY2RLYURVV1ZXaHlNNnhBS1o2a0lhM1ljQUR2MkJBRGc2eFlnYmE0Sk1aMlRDTWpKYgpIYVlsb25QYkFKUXE4YWJ2cFRCL3RNSkk3R1JaR3ZDNTNHWjlUU2RkUzViSFhLWTFsbER5NW1qY1lCL2JBMGFvCjJ3bVVFcHk3MUM0K0paOURxcmxZcVRJVzBhUFhFSDBNNmRyRDJ0TUI2bisyVjA3UFhFVkJGMDZPRWNEVU5GLzMKaTFiV0Jjem1WRFczQlFvT1FIcXF1SDQrQUl0STZuV3pKbXBmSG15R2hkOWhYdS9yM0dCYWpPS1o2WU5YWDRjSgpBWWdBeU1iY3kweHBXOVp6QVVlRTVCc1g2RE9LZTFBSmhuRkZBUWRIQkRkMVAybFdYcVJoYUllM3UvaHdjdjRiCmJ0TllmL0JRVWpYQ3M1aW9kU28zMkdRVVFqRU1USEhrdDl3MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://71955c4f-ee87-408d-8821-7c0c29b0125d.us-east-2.linodelke.net:443
  name: lke51735

users:
- name: lke51735-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InlQZVFPVFJmRW5KS1ZKOTctRGNyUTRpenVZODlZSS05bHhHUGpFNVJjM0EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdzkybG4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGZmMTg2OTEtNjkzZC00YjEzLTg0NTAtZTYwOTk1YmRiYzg5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.cHaxlrM4P7vd7oAnRtdAtr4T_eeg_Lm4aQpdX5vPIdb2jJrVDPKdouXgyo1xL5K3EfbOCUt-SCnyMNou_ryCesBEIiatNu8jNjAKLtGkMFyXEMQ_Lh9cqGEE0NpJitqn1LZ4J-5mxaqX-ER7jg2U2XaRTknguo5LBEDk6HeIJjxEwHbVNj3FHkWvCHOZ_FdFkLGZ2-JVbxk0BbNT6U6WWfotOdNgDeUjeGMdvZESLpSXcHLt1gY91npguIwHvKS2oCOkn_YdBrb_Mpv4la7cEkzWlQqvK70vuYs6EnwdB8DOnF81BmKN1MJTMCT6RCeA1gUvZHyYmCz8AMh-RkB_Qw

contexts:
- context:
    cluster: lke51735
    namespace: default
    user: lke51735-admin
  name: lke51735-ctx

current-context: lke51735-ctx
